# Generated by Django 6.0.3 on 2026-03-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photograph',
            name='category',
            field=models.CharField(choices=[('NEBULOSA', 'Nebulosa'), ('ESTRELA', 'Estrela'), ('GALÁXIA', 'Galáxia'), ('PLANETA', 'Planeta')], default='', max_length=100),
        ),
    ]
