# Generated by Django 6.0.3 on 2026-03-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0002_photograph_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='photograph',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
