# Generated by Django 6.0.3 on 2026-03-19 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0003_photograph_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='photograph',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
