# Generated by Django 6.0.3 on 2026-03-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0004_photograph_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photograph',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d/'),
        ),
    ]
